/-
Copyright (c) 2026 Harrison Totty. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Harrison Totty
-/
import Mathlib.LinearAlgebra.Matrix.Transvection
import Mathlib.Order.Cover
import Mathlib.Tactic
import Theorems.TotallyPositiveKernel

/-!
# The Loewner–Whitney theorem

The **Loewner–Whitney theorem** identifies the invertible totally nonnegative matrices with the
multiplicative monoid generated by *elementary Jacobi matrices* with nonnegative entries —
matrices differing from the identity in a single entry on, immediately above, or immediately
below the main diagonal (Fomin–Zelevinsky *Intelligencer*, Theorem 12; Fallat–Johnson,
Theorem 2.2.2; Loewner 1955, eq. (5), restating A. M. Whitney's 1952 reduction theorem).

Total nonnegativity is `Matrix.IsTotallyNonneg`, defined in `Theorems.TotallyPositiveKernel` and
**not** redefined here. The elementary Jacobi matrix `I + c • E i j` is Mathlib's
`Matrix.transvection i j c`, also not redefined: this module is about which transvections are
totally nonnegative and what their products can be.

## The adjacency hypothesis is the content

Mathlib's `Matrix.transvection` allows any `i ≠ j`, imposes no sign condition, and its
factorization theorem `Matrix.Pivot.exists_list_transvec_mul_diagonal_mul_list_transvec` holds for
an arbitrary matrix over an arbitrary field. Loewner–Whitney is exactly the statement that
restricting to *nonnegative bidiagonal* factors with a *positive* diagonal carves out the
invertible totally nonnegative matrices. Accordingly the two hypotheses that the sources state
informally as "`|i - j| = 1`" and "`t ≥ 0`" are here proved to be sharp:
`Matrix.isTotallyNonneg_transvection_iff` says that for `i < j` and `c > 0` the transvection
`transvection i j c` is totally nonnegative **if and only if** `i ⋖ j`, i.e. `j` covers `i` in the
index order. Phrasing adjacency as `CovBy` rather than as `(i : ℕ) + 1 = j` is what makes the
statement hold over an arbitrary linearly ordered index type, and it is exactly the hypothesis the
proof consumes.

## Scope: what is proved and what is blocked

The **easy direction** of Loewner–Whitney — that every product of nonnegative generators is
totally nonnegative — is closure of `IsTotallyNonneg` under matrix multiplication, which follows
from the Cauchy–Binet formula. **Mathlib has no Cauchy–Binet formula** and no compound-matrix
machinery, so for general `n` both directions are out of reach and are recorded as backlog in the
research notes rather than stated here. At `n = 2` Cauchy–Binet degenerates to multiplicativity of
`det`, so the full biconditional is proved:
`Matrix.isTotallyNonneg_and_det_ne_zero_iff_fin_two`.

## Main statements

* `Matrix.isTotallyNonneg_diagonal` — a diagonal matrix with nonnegative entries is totally
  nonnegative, the second family of generators (Lam, Theorem 2.2).
* `Matrix.isTotallyNonneg_transvection_of_covBy` — an elementary Jacobi matrix `transvection i j c`
  with `0 ≤ c` and `i ⋖ j` is totally nonnegative: Fomin–Zelevinsky (*Intelligencer*), "an easy
  check shows that they are totally nonnegative for any `t > 0`"; Fallat–Johnson §2.1; Higham
  (EJLA 2024), Theorem 5.2. The subdiagonal companion is
  `Matrix.isTotallyNonneg_transvection_of_covBy'`.
* `Matrix.not_isTotallyNonneg_transvection_of_lt_of_lt` — if some index lies strictly between `i`
  and `j` then `transvection i j c` with `c > 0` is *not* totally nonnegative.
* `Matrix.isTotallyNonneg_transvection_iff` — the two combine into a characterization: for `i < j`
  and `0 < c`, `transvection i j c` is totally nonnegative iff `i ⋖ j`. This is the precise form of
  the sources' informal "`|i - j| = 1`", and it is what distinguishes Loewner–Whitney from Mathlib's
  sign-blind transvection factorization.
* `Matrix.isTotallyNonneg_fin_two_iff` and `Matrix.isTotallyPos_fin_two_iff` — total nonnegativity
  (resp. positivity) of a `2 × 2` matrix is five weak (resp. strict) inequalities.
* `Matrix.isTotallyNonneg_and_det_ne_zero_iff_fin_two` — **the Loewner–Whitney theorem at `n = 2`**,
  as a biconditional: a `2 × 2` matrix over an ordered field is totally nonnegative and invertible
  iff it is `transvection 1 0 l * diagonal ![d₀, d₁] * transvection 0 1 u` with `0 ≤ l`, `0 ≤ u`,
  `0 < d₀`, `0 < d₁`. This is Fallat–Johnson's (2.12) at `n = 2` (their §2.3, p. 57) together with
  its converse, their Theorem 2.6.2(1).
* `Matrix.isTotallyPos_iff_exists_fin_two` — Fallat–Johnson Corollary 2.2.3 at `n = 2`: the matrix
  is *totally positive* exactly when both multipliers are strictly positive.
* `LoewnerWhitney.not_exists_jacobiFactorization_ones` — **invertibility cannot be dropped**:
  `!![1, 1; 1, 1]` is totally nonnegative but is not a product of transvections and a positive
  diagonal, because every such product has strictly positive determinant while `det = 0` here.
* `LoewnerWhitney.fallatJohnson_eq_transvection_prod` together with
  `LoewnerWhitney.not_isTotallyNonneg_fallatJohnson` — **the sign condition is what does the
  work**: Fallat–Johnson's cautionary example (§2.1, p. 46) `!![1,0,0; 0,1,0; 1,0,1]` *does* have an
  elementary bidiagonal factorization, with mixed signs, and is not totally nonnegative. Merely
  *having* such a factorization is worthless.

Supporting lemmas about Mathlib objects that Mathlib itself lacks, and that would migrate upstream
unchanged: `Matrix.transpose_transvection`, `Matrix.commute_transvection`,
`Matrix.diagonal_mul_single`, `Matrix.single_mul_diagonal`,
`Matrix.transvection_mul_diagonal_eq_diagonal_mul_transvection`, and
`Matrix.det_submatrix_diagonal_of_ne`.

## Implementation notes

* Adjacency is `CovBy` (`i ⋖ j`), not `(i : ℕ) + 1 = j`. The proof of
  `Matrix.isTotallyNonneg_transvection_of_covBy` consumes exactly "nothing lies strictly between
  `i` and `j`" — when the row sampling is pushed from `i` up to `j`, either it stays strictly
  monotone or it collides with the next sampled row, and the collision is what forces the minor to
  vanish. `CovBy` is therefore the honest hypothesis, and it specializes to `j = i + 1` on `Fin n`.
* The diagonal generator is deliberately `Matrix.diagonal`, not `Matrix.transvection i i (t - 1)`.
  The latter does elaborate — `transvection` does not require `i ≠ j` — but it is a junk value: it
  lies outside the domain of `Matrix.det_transvection_of_ne` and of
  `Matrix.transvection_mul_transvection_same`, both of which carry `i ≠ j` as a hypothesis. The
  statements below whose *truth* depends on separating the indices carry that hypothesis explicitly
  (`Matrix.not_isTotallyNonneg_transvection_of_neg`), or obtain it from a strictly stronger order
  hypothesis (`i ⋖ j`, `i < k < j`), or from the `hij` field of `Matrix.TransvectionStruct`
  (`Matrix.det_pos_of_prod_transvection`). The purely algebraic identities
  (`Matrix.transpose_transvection`, `Matrix.commute_transvection`, the diagonal slide) are stated
  without it because they are true at `i = j` as well; weakening them would be gratuitous.
* Nothing in this file opens `MatrixOrder`. Mathlib's only order instance on `Matrix` is the Loewner
  order, under which `0 ≤ A` means *positive semidefinite*; entrywise nonnegativity is always
  written out as `∀ i j, 0 ≤ A i j`, matching `Matrix.rowStochastic` and `Matrix.IsIrreducible`.
* The two factorization theorems require an ordered **field**, not merely an ordered commutative
  ring: the multipliers are `c / a`, `b / a` and `det A / a`. Over `ℤ` the forward direction is
  false — `!![2, 1; 0, 1]` is totally nonnegative with `det = 2 ≠ 0`, but the product form forces
  `d₀ = 2` and `d₀ * u = 1`, which has no integer solution. Everything upstream of the
  factorizations is stated over an ordered commutative ring, which is all those proofs need.
* The `Fin 3` fixtures are stated over `ℤ` rather than `ℝ`. Concrete determinant goals are
  decidable over `ℤ` and not over `ℝ`, and total nonnegativity is a statement about the ordered
  ring, so the integer fixtures certify the same page claims more cheaply.
* `Matrix.isTotallyNonneg_fin_two_iff` reduces total nonnegativity of a `2 × 2` matrix to five
  inequalities. Minors of size `k ≥ 3` are vacuous because a `StrictMono` map `Fin k → Fin 2`
  forces `k ≤ 2`; this is where the definition's quantifier over all `k` is discharged.
* Index types carry `[LinearOrder n]` alone wherever an order is needed; the `DecidableEq n`
  required by `Matrix.diagonal` and `Matrix.transvection` is taken from that instance rather than
  assumed separately, so that neighbouring lemmas rewrite into one another without
  `Subsingleton.elim`.

## References

* [S. Fomin, A. Zelevinsky, *Total positivity: tests and parametrizations*][fominZelevinsky2000a],
  Math. Intelligencer 22 (2000), 23–33; arXiv:math/9912128. Theorems 11–14, Definition 22,
  Theorems 23–30. Cited here for Proposition 10 (multiplicative closure), Theorem 12 (the
  Loewner–Whitney theorem), and Lemma 15 (positivity of the leading principal minors).
* [S. Fomin, A. Zelevinsky, *Totally nonnegative and oscillatory elements in semisimple
  groups*][fominZelevinsky2000b], Proc. Amer. Math. Soc. 128 (2000), 3749–3759;
  arXiv:math/9811100. Theorem 1.1, the three-way equivalence, and the source that fixes the name
  "Loewner–Whitney theorem".
* [S. M. Fallat, C. R. Johnson, *Totally Nonnegative Matrices*][fallatJohnson2011], Princeton
  University Press, 2011. Definition 2.1.1 (elementary bidiagonal matrices), Theorem 2.2.1
  (Whitney's reduction), Theorem 2.2.2 (the SEB factorization), Corollary 2.2.3 (the totally
  positive case), Theorem 2.6.2(1) (the converse of 2.2.2), the `2 × 2` factorization at §2.3
  p. 57, and the cautionary example at §2.1 p. 46.
* [T. Lam, *Totally nonnegative Grassmannian and Grassmann polytopes*][lam2015], arXiv:1506.00603.
  Theorem 2.2, Loewner–Whitney as an equality of sets, whose generating set is "`{x_i(a)}`,
  `{y_i(a)}`, and diagonal matrices with positive real entries".
* C. W. Cryer, *The LU-factorization of totally positive matrices*, Linear Algebra Appl. 7 (1973),
  83–92, and *Some properties of totally positive matrices*, Linear Algebra Appl. 15 (1976), 1–25.
  The research notes attribute positivity of the leading principal minors to "Cryer, via
  Fomin–Zelevinsky Lemma 15" without saying which of the two papers, so neither is singled out
  here; note Cryer's "TP" is this module's totally nonnegative.
* [C. Loewner, *On totally positive matrices*][loewner1955], Math. Z. 63 (1955), 338–340.
  Equation (5), the explicit bidiagonal product; note Loewner's "totally positive" is this page's
  totally nonnegative.
* [A. M. Whitney, *A reduction theorem for totally positive matrices*][whitney1952], J. d'Analyse
  Math. 2 (1952), 88–92. The reduction lemma the factorization is built on.
* [N. J. Higham, *The power of bidiagonal matrices*][higham2024], Electron. J. Linear Algebra 40
  (2024), 453–474. Theorem 5.2 (nonnegative bidiagonal matrices are totally nonnegative) and
  Theorem 5.4 (the grouped-bidiagonal biconditional, credited there to Gasca–Peña).
* [S. M. Fallat, H. Vishwakarma, *Inequalities for totally nonnegative matrices: Gantmacher–Krein,
  Karlin, and Laplace*][fallatVishwakarma2023], arXiv:2305.16485. Theorem 3.1, the ordered
  double-product form, and the remark that the diagonal factor may be slid to either end.
* [R. Alseidi, M. Margaliot et al., *On the exponent of several classes of oscillatory
  matrices*][alseidi2019], arXiv:1910.10709. Proposition 4, total positivity as strict positivity
  of every SEB multiplier; Remark 1, uniqueness of the SEB factorization.

## Tags

Loewner-Whitney theorem, total positivity, totally nonnegative, elementary Jacobi matrix,
elementary bidiagonal matrix, transvection, bidiagonal factorization, SEB factorization
-/

open Finset

namespace Matrix

/-! ### Elementary Jacobi matrices: transpose, commutation, and the diagonal slide

Lemmas about `Matrix.transvection` and `Matrix.single` that Mathlib does not have. Each is stated
in the generality Mathlib would want, and none mentions total positivity. -/

section Elementary

variable {n : Type*} [DecidableEq n] {R : Type*} [CommRing R]

/-- The transpose of an elementary Jacobi matrix is the elementary Jacobi matrix with the indices
swapped: Fomin–Zelevinsky's `x_{ī}(t) = (x_i(t))ᵀ`. -/
theorem transpose_transvection (i j : n) (c : R) :
    (transvection i j c)ᵀ = transvection j i c := by
  simp [transvection, transpose_add, transpose_one, transpose_single]

/-- Multiplying a diagonal matrix into a matrix unit rescales the entry by the diagonal entry in
the unit's **row**. -/
theorem diagonal_mul_single [Fintype n] (d : n → R) (i j : n) (c : R) :
    diagonal d * single i j c = single i j (d i * c) := by
  ext a b
  rw [diagonal_mul, single_apply, single_apply]
  by_cases h : i = a ∧ j = b
  · rw [if_pos h, if_pos h, h.1]
  · rw [if_neg h, if_neg h, mul_zero]

/-- Multiplying a matrix unit by a diagonal matrix rescales the entry by the diagonal entry in the
unit's **column**. -/
theorem single_mul_diagonal [Fintype n] (d : n → R) (i j : n) (c : R) :
    single i j c * diagonal d = single i j (c * d j) := by
  ext a b
  rw [mul_diagonal, single_apply, single_apply]
  by_cases h : i = a ∧ j = b
  · rw [if_pos h, if_pos h, h.2]
  · rw [if_neg h, if_neg h, zero_mul]

/-- **The diagonal factor slides past an elementary Jacobi matrix**, at the cost of rescaling the
off-diagonal parameter (Fallat–Vishwakarma: `D` "can be made to appear at either end of the
factorization or between any of the elementary bidiagonal factors"). Stated in division-free form,
so it needs no invertibility hypothesis on `d`. -/
theorem transvection_mul_diagonal_eq_diagonal_mul_transvection [Fintype n] (d : n → R) (i j : n)
    (c : R) :
    transvection i j (d i * c) * diagonal d = diagonal d * transvection i j (c * d j) := by
  rw [transvection, transvection, add_mul, one_mul, mul_add, mul_one, single_mul_diagonal,
    diagonal_mul_single, mul_assoc]

/-- **Elementary Jacobi matrices with disjoint index pairs commute** — Fallat–Johnson's relations
(1) `L_i(s)L_j(t) = L_j(t)L_i(s)` for `|i - j| > 1` and (4) `L_i(s)U_j(t) = U_j(t)L_i(s)` for
`i ≠ j`, both of which reduce to the vanishing of the two cross terms. -/
theorem commute_transvection [Fintype n] {i j k l : n} (hjk : j ≠ k) (hli : l ≠ i) (c d : R) :
    Commute (transvection i j c) (transvection k l d) := by
  have h1 : single i j c * single k l d = (0 : Matrix n n R) :=
    single_mul_single_of_ne c i j k hjk d
  have h2 : single k l d * single i j c = (0 : Matrix n n R) :=
    single_mul_single_of_ne d k l i hli c
  show transvection i j c * transvection k l d = transvection k l d * transvection i j c
  simp only [transvection, add_mul, mul_add, one_mul, mul_one, h1, h2]
  abel

end Elementary

/-! ### Minors of a diagonal matrix

A square submatrix of a diagonal matrix sampled at strictly increasing row and column arguments
vanishes unless the two samplings agree. The complementary case — equal samplings — is Mathlib's
`Matrix.submatrix_diagonal`, and the identity case is `Matrix.submatrix_one`. -/

section DiagonalMinors

variable {n : Type*} [LinearOrder n] {R : Type*} [CommRing R] {k : ℕ}

/-- The one-sided form of `Matrix.det_submatrix_diagonal_of_ne`: if the row sampling first falls
strictly below the column sampling at `a₀`, the `a₀`-th row of the minor is identically zero. -/
private theorem det_submatrix_diagonal_of_lt (d : n → R) {f g : Fin k → n} (hf : StrictMono f)
    (hg : StrictMono g) {a₀ : Fin k} (hlt : f a₀ < g a₀)
    (hmin : ∀ b : Fin k, b < a₀ → f b = g b) : ((diagonal d).submatrix f g).det = 0 := by
  refine det_eq_zero_of_row_eq_zero a₀ fun b => ?_
  rw [Matrix.submatrix_apply]
  refine diagonal_apply_ne d ?_
  rcases lt_or_ge b a₀ with hb | hb
  · rw [← hmin b hb]
    exact (hf hb).ne'
  · exact ne_of_lt (hlt.trans_le (hg.monotone hb))

/-- **A minor of a diagonal matrix at differing row and column samplings vanishes.** If `f ≠ g`,
the least index where they differ produces a zero row (or column). The complementary case `f = g`
is Mathlib's `Matrix.submatrix_diagonal` together with `Matrix.det_diagonal`. -/
theorem det_submatrix_diagonal_of_ne (d : n → R) {f g : Fin k → n} (hf : StrictMono f)
    (hg : StrictMono g) (hfg : f ≠ g) : ((diagonal d).submatrix f g).det = 0 := by
  classical
  obtain ⟨a, ha⟩ : ∃ a : Fin k, f a ≠ g a := Function.ne_iff.mp hfg
  set S : Finset (Fin k) := Finset.univ.filter fun a => f a ≠ g a with hS
  have hSne : S.Nonempty := ⟨a, by simp [hS, ha]⟩
  set a₀ := S.min' hSne with ha₀def
  have ha₀ne : f a₀ ≠ g a₀ := by
    have := S.min'_mem hSne
    simpa [hS] using this
  have hmin : ∀ b : Fin k, b < a₀ → f b = g b := by
    intro b hb
    by_contra hbne
    exact absurd (S.min'_le b (by simp [hS, hbne])) (not_le.mpr hb)
  rcases lt_or_gt_of_ne ha₀ne with h | h
  · exact det_submatrix_diagonal_of_lt d hf hg h hmin
  · have hT : ((diagonal d).submatrix f g)ᵀ = (diagonal d).submatrix g f := by
      rw [transpose_submatrix, diagonal_transpose]
    rw [← det_transpose, hT]
    exact det_submatrix_diagonal_of_lt d hg hf h fun b hb => (hmin b hb).symm

/-- A minor of the identity matrix at differing strictly increasing samplings vanishes: the
`d = 1` case of `Matrix.det_submatrix_diagonal_of_ne`. -/
theorem det_submatrix_one_of_ne {f g : Fin k → n} (hf : StrictMono f) (hg : StrictMono g)
    (hfg : f ≠ g) : ((1 : Matrix n n R).submatrix f g).det = 0 := by
  rw [← diagonal_one]
  exact det_submatrix_diagonal_of_ne _ hf hg hfg

end DiagonalMinors

/-! ### The generators are totally nonnegative

Fomin–Zelevinsky's two families of generators: positive diagonal matrices, and elementary Jacobi
matrices with a nonnegative parameter on the first sub- or superdiagonal. -/

section Generators

variable {n : Type*} [LinearOrder n] {R : Type*} [CommRing R] [PartialOrder R] [IsOrderedRing R]

/-- **A diagonal matrix with nonnegative entries is totally nonnegative.** These are
Fomin–Zelevinsky's generators `x_{∘i}(t)`, and Thomas Lam's "diagonal matrices with positive real
entries" (Theorem 2.2) once the entries are required strictly positive. -/
theorem isTotallyNonneg_diagonal {d : n → R} (hd : ∀ i : n, 0 ≤ d i) :
    (diagonal d).IsTotallyNonneg := by
  intro k f g hf hg
  by_cases h : f = g
  · subst h
    rw [Matrix.submatrix_diagonal d f hf.injective, det_diagonal]
    exact Finset.prod_nonneg fun i _ => hd (f i)
  · rw [det_submatrix_diagonal_of_ne d hf hg h]

/-- The identity matrix is totally nonnegative. -/
theorem isTotallyNonneg_one : (1 : Matrix n n R).IsTotallyNonneg := by
  rw [← diagonal_one]
  exact isTotallyNonneg_diagonal fun _ => zero_le_one

/-- **An elementary Jacobi matrix with a nonnegative parameter on the first superdiagonal is
totally nonnegative** (Fomin–Zelevinsky, *Intelligencer*: "an easy check shows that they are
totally nonnegative for any `t > 0`"; Fallat–Johnson §2.1: "any EB matrix is (invertible) TN
whenever `s, t ≥ 0`"; Higham, EJLA 2024, Theorem 5.2). The hypothesis `i ⋖ j` — `j` covers `i`, so
no index lies strictly between them — is the order-theoretic form of the sources' `|i - j| = 1`,
and by
`Matrix.not_isTotallyNonneg_transvection_of_lt_of_lt` it cannot be weakened. -/
theorem isTotallyNonneg_transvection_of_covBy {i j : n} (hij : i ⋖ j) {c : R} (hc : 0 ≤ c) :
    (transvection i j c).IsTotallyNonneg := by
  classical
  intro k f g hf hg
  -- Every minor of the identity sampled at a strictly monotone row map is `0` or `1`.
  have hone : ∀ p : Fin k → n, StrictMono p → 0 ≤ ((1 : Matrix n n R).submatrix p g).det := by
    intro p hp
    by_cases h : p = g
    · subst h
      rw [Matrix.submatrix_one p hp.injective, det_one]
      exact zero_le_one
    · rw [det_submatrix_one_of_ne hp hg h]
  by_cases hi : ∃ a₀ : Fin k, f a₀ = i
  · obtain ⟨a₀, ha₀⟩ := hi
    -- Only row `a₀` sees the off-diagonal entry, so the minor is linear in that row.
    have key : (transvection i j c).submatrix f g
        = ((1 : Matrix n n R).submatrix f g).updateRow a₀
            (((1 : Matrix n n R).submatrix f g) a₀ + c • fun b => if j = g b then (1 : R) else 0) := by
      ext a b
      rw [Matrix.updateRow_apply]
      rcases eq_or_ne a a₀ with rfl | ha
      · rw [if_pos rfl]
        simp only [Matrix.submatrix_apply, transvection, Matrix.add_apply, single_apply,
          Pi.add_apply, Pi.smul_apply, smul_eq_mul]
        congr 1
        by_cases hjb : j = g b
        · rw [if_pos ⟨ha₀.symm, hjb⟩, if_pos hjb, mul_one]
        · rw [if_neg fun hcon => hjb hcon.2, if_neg hjb, mul_zero]
      · rw [if_neg ha]
        simp only [Matrix.submatrix_apply, transvection, Matrix.add_apply, single_apply]
        rw [if_neg fun hcon => ha (hf.injective (hcon.1.symm.trans ha₀.symm)), add_zero]
    rw [key, det_updateRow_add, Matrix.updateRow_eq_self, det_updateRow_smul]
    -- Replacing row `a₀` by the indicator of `j` re-samples the identity along `update f a₀ j`.
    have hrow : ((1 : Matrix n n R).submatrix f g).updateRow a₀
        (fun b => if j = g b then (1 : R) else 0)
        = (1 : Matrix n n R).submatrix (Function.update f a₀ j) g := by
      ext a b
      simp only [Matrix.updateRow_apply, Matrix.submatrix_apply]
      rcases eq_or_ne a a₀ with rfl | ha
      · rw [if_pos rfl, Function.update_self, one_apply]
      · rw [if_neg ha, Function.update_of_ne ha]
    rw [hrow]
    refine add_nonneg (hone f hf) (mul_nonneg hc ?_)
    by_cases hj : ∃ a₁ : Fin k, f a₁ = j
    · -- The pushed row collides with the row already sampling `j`.
      obtain ⟨a₁, ha₁⟩ := hj
      have hne : a₀ ≠ a₁ := by
        rintro rfl
        exact hij.1.ne (ha₀.symm.trans ha₁)
      refine le_of_eq (det_zero_of_row_eq hne ?_).symm
      funext b
      rw [Matrix.submatrix_apply, Matrix.submatrix_apply, Function.update_self,
        Function.update_of_ne hne.symm, ha₁]
    · -- Otherwise the pushed sampling is still strictly monotone, and `i ⋖ j` is what proves it.
      replace hj := not_exists.mp hj
      refine hone _ fun a b hab => ?_
      rcases eq_or_ne a a₀ with rfl | ha
      · rw [Function.update_self, Function.update_of_ne (ne_of_lt hab).symm]
        have h1 : i < f b := by rw [← ha₀]; exact hf hab
        rcases lt_trichotomy (f b) j with h2 | h2 | h2
        · exact absurd h2 (hij.2 h1)
        · exact absurd h2 (hj b)
        · exact h2
      · rcases eq_or_ne b a₀ with rfl | hb
        · rw [Function.update_of_ne ha, Function.update_self]
          have h1 : f a < i := by rw [← ha₀]; exact hf hab
          exact h1.trans hij.1
        · rw [Function.update_of_ne ha, Function.update_of_ne hb]
          exact hf hab
  · -- No sampled row hits `i`, so the transvection is invisible to this minor.
    replace hi := not_exists.mp hi
    have hEq : (transvection i j c).submatrix f g = (1 : Matrix n n R).submatrix f g := by
      ext a b
      simp only [Matrix.submatrix_apply, transvection, Matrix.add_apply, single_apply]
      rw [if_neg fun hcon => hi a hcon.1.symm, add_zero]
    rw [hEq]
    exact hone f hf

/-- The subdiagonal companion of `Matrix.isTotallyNonneg_transvection_of_covBy`, obtained by
transposition: Fallat–Johnson's `L_i(s)` to the former's `U_j(t)`. -/
theorem isTotallyNonneg_transvection_of_covBy' {i j : n} (hij : j ⋖ i) {c : R} (hc : 0 ≤ c) :
    (transvection i j c).IsTotallyNonneg := by
  have h := (isTotallyNonneg_transvection_of_covBy hij hc).transpose
  rwa [transpose_transvection] at h

end Generators

/-! ### Adjacency is necessary

The counterexample that makes `CovBy` the right hypothesis, and hence distinguishes the
Loewner–Whitney generators from Mathlib's unrestricted transvections. -/

section Necessity

variable {n : Type*} [LinearOrder n] {R : Type*} [CommRing R] [PartialOrder R]
  [IsStrictOrderedRing R]

/-- **A non-adjacent elementary matrix is not totally nonnegative.** If `i < k < j` then the minor
of `transvection i j c` on rows `{i, k}` and columns `{k, j}` equals `-c`. This is why the
Loewner–Whitney generators must be *bidiagonal*: Mathlib's `Matrix.transvection` allows any
`i ≠ j`, and the extra freedom immediately leaves the totally nonnegative cone. -/
theorem not_isTotallyNonneg_transvection_of_lt_of_lt {i j k : n} (hik : i < k) (hkj : k < j)
    {c : R} (hc : 0 < c) : ¬ (transvection i j c).IsTotallyNonneg := by
  intro h
  have e00 : (transvection i j c) i k = 0 := by
    simp [transvection, hik.ne, hkj.ne']
  have e01 : (transvection i j c) i j = c := by
    simp [transvection, (hik.trans hkj).ne]
  have e10 : (transvection i j c) k k = 1 := by
    simp [transvection, hik.ne]
  have e11 : (transvection i j c) k j = 0 := by
    simp [transvection, hkj.ne, hik.ne]
  have h2 := h 2 ![i, k] ![k, j] (strictMono_fin_two hik) (strictMono_fin_two hkj)
  rw [det_fin_two] at h2
  simp only [Matrix.submatrix_apply, Matrix.cons_val_zero, Matrix.cons_val_one,
    e00, e01, e10, e11] at h2
  rw [mul_zero, mul_one, zero_sub, neg_nonneg] at h2
  exact absurd (hc.trans_le h2) (lt_irrefl 0)

omit [IsStrictOrderedRing R] in
/-- **A negative parameter is not totally nonnegative**, immediately from the `1 × 1` minor at
`(i, j)`. -/
theorem not_isTotallyNonneg_transvection_of_neg {i j : n} (hij : i ≠ j) {c : R} (hc : c < 0) :
    ¬ (transvection i j c).IsTotallyNonneg := by
  intro h
  have hentry : (transvection i j c) i j = c := by
    simp [transvection, hij]
  have hnn := h.entry_nonneg i j
  rw [hentry] at hnn
  exact absurd (hc.trans_le hnn) (lt_irrefl c)

/-- **Total nonnegativity of an elementary matrix is exactly adjacency.** For `i < j` and a
strictly positive parameter, `transvection i j c` is totally nonnegative if and only if `j` covers
`i`. This is the sharp form of the sources' informal `|i - j| = 1`, and the precise sense in which
Loewner–Whitney's generating set is smaller than Mathlib's set of transvections. -/
theorem isTotallyNonneg_transvection_iff {i j : n} (hij : i < j) {c : R} (hc : 0 < c) :
    (transvection i j c).IsTotallyNonneg ↔ i ⋖ j := by
  refine ⟨fun h => ⟨hij, fun x hix hxj => ?_⟩,
    fun h => isTotallyNonneg_transvection_of_covBy h hc.le⟩
  exact not_isTotallyNonneg_transvection_of_lt_of_lt hix hxj hc h

end Necessity

/-! ### Total positivity of `2 × 2` matrices

At `n = 2` the Cauchy–Binet formula degenerates to multiplicativity of the determinant, so the
easy direction of Loewner–Whitney is available. -/

section FinTwoBasic

variable {R : Type*} [CommRing R] [PartialOrder R] [IsStrictOrderedRing R]

/-- A strictly monotone self-map of `Fin 2` is the identity. This is what discharges the `k = 2`
case of the `2 × 2` characterizations: the only minor of full size is the determinant itself. -/
private theorem strictMono_fin_two_eq_id {f : Fin 2 → Fin 2} (hf : StrictMono f) : f = id := by
  have h1 : (f 0 : ℕ) < (f 1 : ℕ) := hf (by decide)
  have h0 : (f 0 : ℕ) < 2 := (f 0).isLt
  have h2 : (f 1 : ℕ) < 2 := (f 1).isLt
  funext x
  fin_cases x
  · exact Fin.ext (by simpa using by omega)
  · exact Fin.ext (by simpa using by omega)

omit [PartialOrder R] [IsStrictOrderedRing R] in
/-- Total nonnegativity and total positivity of a `2 × 2` matrix are each determined by the four
entries and the determinant; this packages the shared quantifier bookkeeping over minor sizes. -/
private theorem forall_strictMono_fin_two {P : R → Prop} (hP : P 1)
    (A : Matrix (Fin 2) (Fin 2) R) (hentry : ∀ x y : Fin 2, P (A x y)) (hdet : P A.det)
    (k : ℕ) (f g : Fin k → Fin 2) (hf : StrictMono f) (hg : StrictMono g) :
    P ((A.submatrix f g).det) := by
  have hk : k ≤ 2 := by simpa using Fintype.card_le_of_injective f hf.injective
  interval_cases k
  · rwa [det_fin_zero]
  · rw [det_fin_one, Matrix.submatrix_apply]
    exact hentry _ _
  · rw [strictMono_fin_two_eq_id hf, strictMono_fin_two_eq_id hg, Matrix.submatrix_id_id]
    exact hdet

/-- **Total nonnegativity of a `2 × 2` matrix is five inequalities**: the four entries and the
determinant. Minors of size `k ≥ 3` are vacuous, since a `StrictMono` map `Fin k → Fin 2` forces
`k ≤ 2`. -/
theorem isTotallyNonneg_fin_two_iff (A : Matrix (Fin 2) (Fin 2) R) :
    A.IsTotallyNonneg ↔ 0 ≤ A 0 0 ∧ 0 ≤ A 0 1 ∧ 0 ≤ A 1 0 ∧ 0 ≤ A 1 1 ∧ 0 ≤ A.det := by
  constructor
  · intro h
    refine ⟨h.entry_nonneg 0 0, h.entry_nonneg 0 1, h.entry_nonneg 1 0, h.entry_nonneg 1 1, ?_⟩
    simpa using h 2 id id strictMono_id strictMono_id
  · rintro ⟨h00, h01, h10, h11, hdet⟩
    have hentry : ∀ x y : Fin 2, 0 ≤ A x y := by
      intro x y
      fin_cases x <;> fin_cases y <;> assumption
    exact forall_strictMono_fin_two zero_le_one A hentry hdet

/-- **Total positivity of a `2 × 2` matrix is five strict inequalities.** -/
theorem isTotallyPos_fin_two_iff (A : Matrix (Fin 2) (Fin 2) R) :
    A.IsTotallyPos ↔ 0 < A 0 0 ∧ 0 < A 0 1 ∧ 0 < A 1 0 ∧ 0 < A 1 1 ∧ 0 < A.det := by
  constructor
  · intro h
    refine ⟨h.entry_pos 0 0, h.entry_pos 0 1, h.entry_pos 1 0, h.entry_pos 1 1, ?_⟩
    simpa using h 2 id id strictMono_id strictMono_id
  · rintro ⟨h00, h01, h10, h11, hdet⟩
    have hentry : ∀ x y : Fin 2, 0 < A x y := by
      intro x y
      fin_cases x <;> fin_cases y <;> assumption
    exact forall_strictMono_fin_two zero_lt_one A hentry hdet

/-- **Totally nonnegative `2 × 2` matrices are closed under multiplication** — Fomin–Zelevinsky's
Proposition 10 (*Intelligencer*) at `n = 2`. For general `n` this is a corollary of the
Cauchy–Binet formula, which Mathlib does not have; at `n = 2` the only minor that needs an
argument is the determinant, and `Matrix.det_mul` supplies it. -/
theorem IsTotallyNonneg.mul_fin_two {A B : Matrix (Fin 2) (Fin 2) R} (hA : A.IsTotallyNonneg)
    (hB : B.IsTotallyNonneg) : (A * B).IsTotallyNonneg := by
  rw [isTotallyNonneg_fin_two_iff] at hA hB ⊢
  obtain ⟨a00, a01, a10, a11, adet⟩ := hA
  obtain ⟨b00, b01, b10, b11, bdet⟩ := hB
  have hmul : ∀ x y : Fin 2, 0 ≤ (A * B) x y := by
    intro x y
    rw [Matrix.mul_apply, Fin.sum_univ_two]
    have hx : ∀ z : Fin 2, 0 ≤ A x z := by fin_cases x <;> intro z <;> fin_cases z <;> assumption
    have hy : ∀ z : Fin 2, 0 ≤ B z y := by fin_cases y <;> intro z <;> fin_cases z <;> assumption
    exact add_nonneg (mul_nonneg (hx 0) (hy 0)) (mul_nonneg (hx 1) (hy 1))
  exact ⟨hmul 0 0, hmul 0 1, hmul 1 0, hmul 1 1, by rw [det_mul]; exact mul_nonneg adet bdet⟩

/-- **The leading entry of a totally nonnegative `2 × 2` matrix with nonzero determinant is
positive** (Cryer, via Fomin–Zelevinsky *Intelligencer* Lemma 15, at `n = 2`). This is what
makes the elimination well defined: the pivot cannot vanish. The hypothesis is `A.det ≠ 0` rather
than invertibility of `A`, which is strictly weaker over a general ordered commutative ring — over
`ℤ`, `!![2, 0; 0, 3]` has nonzero determinant and no inverse — and is all the proof uses. -/
theorem pos_of_isTotallyNonneg_fin_two {A : Matrix (Fin 2) (Fin 2) R} (hA : A.IsTotallyNonneg)
    (hdet : A.det ≠ 0) : 0 < A 0 0 := by
  rw [isTotallyNonneg_fin_two_iff] at hA
  obtain ⟨h00, h01, h10, h11, hdetnn⟩ := hA
  refine h00.lt_of_ne fun hzero => hdet ?_
  rw [det_fin_two, ← hzero, zero_mul, zero_sub] at hdetnn ⊢
  have hprod : 0 ≤ A 0 1 * A 1 0 := mul_nonneg h01 h10
  exact le_antisymm (neg_nonpos.mpr hprod) hdetnn

end FinTwoBasic

/-! ### The Loewner–Whitney theorem at `n = 2`

These two statements need an ordered **field**: the multipliers are quotients by the pivot. See the
implementation notes for the integer counterexample. -/

section FinTwoFactorization

variable {R : Type*} [Field R] [LinearOrder R] [IsStrictOrderedRing R]

omit [LinearOrder R] [IsStrictOrderedRing R] in
/-- The `2 × 2` Loewner–Whitney product, computed. `transvection 1 0 l` is lower unit bidiagonal
and `transvection 0 1 u` upper, matching Fallat–Johnson's `L₂(l)` and `U₂(u)`. -/
private theorem transvection_mul_diagonal_mul_transvection_fin_two (l u d₀ d₁ : R) :
    (transvection 1 0 l * diagonal ![d₀, d₁] * transvection 0 1 u : Matrix (Fin 2) (Fin 2) R)
      = !![d₀, d₀ * u; l * d₀, l * d₀ * u + d₁] := by
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [transvection, Matrix.mul_apply, Fin.sum_univ_two, single_apply, one_apply,
      Matrix.diagonal_apply]

/-- **The Loewner–Whitney theorem for `2 × 2` matrices.** A `2 × 2` matrix over an ordered field is
totally nonnegative and invertible if and only if it factors as a nonnegative lower elementary
bidiagonal matrix, a positive diagonal matrix, and a nonnegative upper elementary bidiagonal matrix.

This is Fallat–Johnson's (2.12) at `n = 2` — printed in their §2.3, p. 57, as
`!![a, b; c, d] = !![1, 0; c / a, 1] * !![a, 0; 0, (a * d - b * c) / a] * !![1, b / a; 0, 1]` for
`a > 0` — together with its converse, their Theorem 2.6.2(1). The forward direction packages
Whitney's single elimination step; the backward direction is the easy half, by
`Matrix.IsTotallyNonneg.mul_fin_two`. -/
theorem isTotallyNonneg_and_det_ne_zero_iff_fin_two (A : Matrix (Fin 2) (Fin 2) R) :
    (A.IsTotallyNonneg ∧ A.det ≠ 0) ↔
      ∃ l u d₀ d₁ : R, 0 ≤ l ∧ 0 ≤ u ∧ 0 < d₀ ∧ 0 < d₁ ∧
        A = transvection 1 0 l * diagonal ![d₀, d₁] * transvection 0 1 u := by
  constructor
  · rintro ⟨hA, hdet⟩
    have hpos : 0 < A 0 0 := pos_of_isTotallyNonneg_fin_two hA hdet
    have hne : A 0 0 ≠ 0 := hpos.ne'
    obtain ⟨h00, h01, h10, h11, hdetnn⟩ := (isTotallyNonneg_fin_two_iff A).mp hA
    have hdetpos : 0 < A.det := hdetnn.lt_of_ne (Ne.symm hdet)
    refine ⟨A 1 0 / A 0 0, A 0 1 / A 0 0, A 0 0, A.det / A 0 0, div_nonneg h10 hpos.le,
      div_nonneg h01 hpos.le, hpos, div_pos hdetpos hpos, ?_⟩
    rw [transvection_mul_diagonal_mul_transvection_fin_two]
    have hdet2 : A.det = A 0 0 * A 1 1 - A 0 1 * A 1 0 := det_fin_two A
    ext a b
    fin_cases a <;> fin_cases b <;> simp [hdet2] <;> field_simp
    ring
  · rintro ⟨l, u, d₀, d₁, hl, hu, hd₀, hd₁, rfl⟩
    rw [transvection_mul_diagonal_mul_transvection_fin_two]
    have hdet : (!![d₀, d₀ * u; l * d₀, l * d₀ * u + d₁] : Matrix (Fin 2) (Fin 2) R).det
        = d₀ * d₁ := by
      rw [det_fin_two_of]; ring
    refine ⟨(isTotallyNonneg_fin_two_iff _).mpr ⟨?_, ?_, ?_, ?_, ?_⟩, ?_⟩
    · simpa using hd₀.le
    · simpa using mul_nonneg hd₀.le hu
    · simpa using mul_nonneg hl hd₀.le
    · simpa using add_nonneg (mul_nonneg (mul_nonneg hl hd₀.le) hu) hd₁.le
    · rw [hdet]; exact (mul_pos hd₀ hd₁).le
    · rw [hdet]; exact (mul_pos hd₀ hd₁).ne'

/-- **The totally positive part is the strictly-positive-multiplier locus** (Fallat–Johnson
Corollary 2.2.3, at `n = 2`; Alseidi et al., Proposition 4: "a matrix `A` is TP if and only if in
the SEB factorization all the multipliers are positive"). Contrast
`Matrix.isTotallyNonneg_and_det_ne_zero_iff_fin_two`, where the multipliers are only `≥ 0`. -/
theorem isTotallyPos_iff_exists_fin_two (A : Matrix (Fin 2) (Fin 2) R) :
    A.IsTotallyPos ↔
      ∃ l u d₀ d₁ : R, 0 < l ∧ 0 < u ∧ 0 < d₀ ∧ 0 < d₁ ∧
        A = transvection 1 0 l * diagonal ![d₀, d₁] * transvection 0 1 u := by
  constructor
  · intro hA
    obtain ⟨h00, h01, h10, h11, hdetpos⟩ := (isTotallyPos_fin_two_iff A).mp hA
    have hne : A 0 0 ≠ 0 := h00.ne'
    refine ⟨A 1 0 / A 0 0, A 0 1 / A 0 0, A 0 0, A.det / A 0 0, div_pos h10 h00,
      div_pos h01 h00, h00, div_pos hdetpos h00, ?_⟩
    rw [transvection_mul_diagonal_mul_transvection_fin_two]
    have hdet2 : A.det = A 0 0 * A 1 1 - A 0 1 * A 1 0 := det_fin_two A
    ext a b
    fin_cases a <;> fin_cases b <;> simp [hdet2] <;> field_simp
    ring
  · rintro ⟨l, u, d₀, d₁, hl, hu, hd₀, hd₁, rfl⟩
    rw [transvection_mul_diagonal_mul_transvection_fin_two]
    have hdet : (!![d₀, d₀ * u; l * d₀, l * d₀ * u + d₁] : Matrix (Fin 2) (Fin 2) R).det
        = d₀ * d₁ := by
      rw [det_fin_two_of]; ring
    refine (isTotallyPos_fin_two_iff _).mpr ⟨?_, ?_, ?_, ?_, ?_⟩
    · simpa using hd₀
    · simpa using mul_pos hd₀ hu
    · simpa using mul_pos hl hd₀
    · simpa using add_pos (mul_pos (mul_pos hl hd₀) hu) hd₁
    · rw [hdet]; exact mul_pos hd₀ hd₁

end FinTwoFactorization

/-! ### Determinants of Loewner–Whitney products -/

section Det

variable {n : Type*} [DecidableEq n] [Fintype n] {R : Type*} [CommRing R] [PartialOrder R]
  [IsStrictOrderedRing R]

/-- **Every Loewner–Whitney product has strictly positive determinant**: each transvection has
determinant `1` and the diagonal factor has strictly positive determinant. This is the obstruction
that rules out singular totally nonnegative matrices. -/
theorem det_pos_of_prod_transvection (L L' : List (TransvectionStruct n R)) {d : n → R}
    (hd : ∀ i : n, 0 < d i) :
    0 < ((L.map TransvectionStruct.toMatrix).prod * diagonal d *
      (L'.map TransvectionStruct.toMatrix).prod).det := by
  rw [det_mul, det_mul, TransvectionStruct.det_toMatrix_prod,
    TransvectionStruct.det_toMatrix_prod, det_diagonal, one_mul, mul_one]
  exact Finset.prod_pos fun i _ => hd i

end Det

end Matrix

namespace LoewnerWhitney

open Matrix

/-! ### Canonical examples

The page's test fixtures, transcribed as theorems. The `Fin 3` fixtures are over `ℤ`, where
concrete determinant goals are decidable. -/

/-- The all-ones `2 × 2` matrix is totally nonnegative: its entries are `1` and its determinant is
`0`. -/
theorem isTotallyNonneg_ones_fin_two :
    (!![1, 1; 1, 1] : Matrix (Fin 2) (Fin 2) ℝ).IsTotallyNonneg := by
  rw [isTotallyNonneg_fin_two_iff]
  norm_num

/-- The all-ones `2 × 2` matrix is singular. -/
theorem det_ones_fin_two : (!![1, 1; 1, 1] : Matrix (Fin 2) (Fin 2) ℝ).det = 0 := by
  norm_num

/-- **Invertibility cannot be dropped from the Loewner–Whitney theorem.** `!![1, 1; 1, 1]` is
totally nonnegative, but every product of transvections with a positive diagonal has strictly
positive determinant, while this matrix is singular. So the totally nonnegative matrices are
strictly larger than the monoid generated by the nonnegative elementary Jacobi matrices; the
theorem's non-singularity hypothesis is necessary, not cosmetic. (Contrast Whitney's *density*
theorem, which needs no invertibility.) -/
theorem not_exists_jacobiFactorization_ones :
    ¬ ∃ (L L' : List (TransvectionStruct (Fin 2) ℝ)) (d : Fin 2 → ℝ),
        (∀ i : Fin 2, 0 < d i) ∧
        (!![1, 1; 1, 1] : Matrix (Fin 2) (Fin 2) ℝ) =
          (L.map TransvectionStruct.toMatrix).prod * diagonal d *
            (L'.map TransvectionStruct.toMatrix).prod := by
  rintro ⟨L, L', d, hd, heq⟩
  have hpos := det_pos_of_prod_transvection L L' hd
  rw [← heq, det_ones_fin_two] at hpos
  exact lt_irrefl 0 hpos

/-- **Fallat–Johnson's cautionary example** (§2.1, p. 46): the matrix `!![1,0,0; 0,1,0; 1,0,1]`
*does* factor into elementary bidiagonal matrices, namely
`L₂(-1) L₃(1) L₂(1) L₃(-1)` in their row-indexed notation `L_i(s) = I + s E_{i, i-1}`. -/
theorem fallatJohnson_eq_transvection_prod :
    (transvection 1 0 (-1) * transvection 2 1 1 * transvection 1 0 1 * transvection 2 1 (-1) :
      Matrix (Fin 3) (Fin 3) ℤ) = !![1, 0, 0; 0, 1, 0; 1, 0, 1] := by
  decide

/-- **…but it is not totally nonnegative**: its minor on rows `{1, 2}` and columns `{0, 1}` is `-1`.
Together with `LoewnerWhitney.fallatJohnson_eq_transvection_prod` this certifies the sharpest
one-sidedness on the page: merely *having* an elementary bidiagonal factorization is worthless, and
only factorizations with **nonnegative** multipliers characterize total nonnegativity. -/
theorem not_isTotallyNonneg_fallatJohnson :
    ¬ (!![1, 0, 0; 0, 1, 0; 1, 0, 1] : Matrix (Fin 3) (Fin 3) ℤ).IsTotallyNonneg := by
  intro h
  have h2 := h 2 ![1, 2] ![0, 1] (strictMono_fin_two (by decide))
    (strictMono_fin_two (by decide))
  revert h2
  decide

/-- The non-adjacent elementary matrix `1 + 2 E₀₂` on `Fin 3` is not totally nonnegative: the minor
on rows `{0, 1}` and columns `{1, 2}` is `-2`. The concrete instance of
`Matrix.not_isTotallyNonneg_transvection_of_lt_of_lt`. -/
theorem not_isTotallyNonneg_transvection_zero_two :
    ¬ (transvection 0 2 2 : Matrix (Fin 3) (Fin 3) ℤ).IsTotallyNonneg :=
  not_isTotallyNonneg_transvection_of_lt_of_lt (k := 1) (by decide) (by decide) (by norm_num)

/-- The adjacent elementary matrix `1 + 2 E₀₁` on `Fin 3` *is* totally nonnegative — the positive
half of the same comparison. -/
theorem isTotallyNonneg_transvection_zero_one :
    (transvection 0 1 2 : Matrix (Fin 3) (Fin 3) ℤ).IsTotallyNonneg :=
  isTotallyNonneg_transvection_of_covBy ⟨by decide, by decide⟩ (by norm_num)

end LoewnerWhitney
